## Outline
* PyTorch
* What are tensors
* Initialising, slicing, reshaping tensors
* Numpy and PyTorch interfacing
* GPU support for PyTorch + Enabling GPUs on Google Colab
* Speed comparisons, Numpy -- PyTorch -- PyTorch on GPU
* Autodiff concepts and application
* Writing a basic learning loop using autograd
* Exercises

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

## Initialise tensors

In [2]:
x = torch.ones(3, 2)
print(x)
x = torch.zeros(3, 2)
print(x)
x = torch.rand(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.8788, 0.7820],
        [0.4941, 0.4449],
        [0.9090, 0.9033]])


In [3]:
x = torch.empty(3, 2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[0.0000e+00, 0.0000e+00],
        [8.4078e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
x = torch.linspace(0, 1, steps=5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [5]:
x = torch.tensor([[1, 2], 
                 [3, 4], 
                 [5, 6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


## Slicing tensors

In [6]:
print(x.size())
print(x[:, 1]) 
print(x[0, :]) 

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [7]:
y = x[1, 1]
print(y)
print(y.item())

tensor(4)
4


## Reshaping tensors

In [8]:
print(x)
y = x.view(2, 3)
print(y)
# if you see x and y both are having different shape

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
y = x.view(6,-1) 
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


## Simple Tensor Operations

In [10]:
x = torch.ones([3, 2])
y = torch.ones([3, 2])
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [11]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [12]:
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


## Numpy <> PyTorch

In [13]:
x_np = x.numpy()
print(type(x), type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a), type(a_pt))
print(a_pt)

[ 2.10031183  0.88365231 -1.0617311  -0.8472951  -1.35443557]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([ 2.1003,  0.8837, -1.0617, -0.8473, -1.3544], dtype=torch.float64)


In [15]:
np.add(a, 1, out=a)
print(a)
print(a_pt) 

[ 3.10031183  1.88365231 -0.0617311   0.1527049  -0.35443557]
tensor([ 3.1003,  1.8837, -0.0617,  0.1527, -0.3544], dtype=torch.float64)


In [17]:
%%time
for i in range(100):
    a = np.random.randn(100,100)
    b = np.random.randn(100,100)
    c = np.matmul(a, b)

Wall time: 68.5 ms


In [18]:
%%time
for i in range(100):
    a = torch.randn([100, 100])
    b = torch.randn([100, 100])
    c = torch.matmul(a, b)

Wall time: 22.8 ms


In [19]:
%%time
for i in range(10):
    a = np.random.randn(10000,10000)
    b = np.random.randn(10000,10000)
    c = a + b

Wall time: 50.7 s


In [20]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000])
    b = torch.randn([10000, 10000])
    c = a + b

Wall time: 15 s


We can clearly see above that time taken by torch is smaller compare to numpy


## CUDA support

In [21]:
print(torch.cuda.device_count())

1


In [22]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

GeForce RTX 2070 with Max-Q Design


In [23]:
cuda0 = torch.device('cuda:0')

In [24]:
a = torch.ones(3, 2, device=cuda0)
b = torch.ones(3, 2, device=cuda0)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [25]:
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')


In [27]:
%%time
for i in range(10):
    a = np.random.randn(10000,10000)
    b = np.random.randn(10000,10000)
    np.add(b, a)

Wall time: 50.9 s


In [28]:
%%time
for i in range(10):
    a_cpu = torch.randn([10000, 10000])
    b_cpu = torch.randn([10000, 10000])
    b_cpu.add_(a_cpu)

Wall time: 14.8 s


In [29]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000], device=cuda0)
    b = torch.randn([10000, 10000], device=cuda0)
    b.add_(a)
# Once a, b, c are run on cuda it improves the time further

Wall time: 194 ms


In [30]:
%%time
for i in range(10):
    a = np.random.randn(10000,10000)
    b = np.random.randn(10000,10000)
    np.matmul(b, a)

Wall time: 2min 16s


In [31]:
%%time
for i in range(10):
    a_cpu = torch.randn([10000, 10000])
    b_cpu = torch.randn([10000, 10000])
    torch.matmul(a_cpu, b_cpu)

Wall time: 58.7 s


In [32]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000], device=cuda0)
    b = torch.randn([10000, 10000], device=cuda0)
    torch.matmul(a, b)

Wall time: 810 ms


## Autodiff

In [33]:
x = torch.ones([3, 2], requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [34]:
y = x + 5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [35]:
z = y*y + 1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [36]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [37]:
t.backward()

In [38]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


$t = \sum_i z_i, z_i = y_i^2 + 1, y_i = x_i + 5$

$\frac{\partial t}{\partial x_i} = \frac{\partial z_i}{\partial x_i} = \frac{\partial z_i}{\partial y_i} \frac{\partial y_i}{\partial x_i} = 2y_i \times 1$


At x = 1, y = 6, $\frac{\partial t}{\partial x_i} = 12$

In [39]:
x = torch.ones([3, 2], requires_grad=True)
y = x + 5
r = 1/(1 + torch.exp(-y))
print(r)
s = torch.sum(r)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [40]:
x = torch.ones([3, 2], requires_grad=True)
y = x + 5
r = 1/(1 + torch.exp(-y))
a = torch.ones([3, 2])
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


$\frac{\partial{s}}{\partial{x}} = \frac{\partial{s}}{\partial{r}} \cdot \frac{\partial{r}}{\partial{x}}$

For the above code $a$ represents $\frac{\partial{s}}{\partial{r}}$ and then $x.grad$ gives directly $\frac{\partial{s}}{\partial{x}}$



## Autodiff example that looks like what we have been doing

In [41]:
x = torch.randn([20, 1], requires_grad=True)
y = 3*x - 2

In [42]:
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

y_hat = w*x + b

loss = torch.sum((y_hat - y)**2)


In [43]:
print(loss)

tensor(493.8129, grad_fn=<SumBackward0>)


In [44]:
loss.backward()

In [45]:
print(w.grad, b.grad)

tensor([-237.7638]) tensor([170.6994])


## Do it in a loop

In [46]:
learning_rate = 0.01

w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

print(w.item(), b.item())

for i in range(10):
    x = torch.randn([20, 1])
    y = 3*x - 2
    y_hat = w*x + b
    loss = torch.sum((y_hat - y)**2)
    loss.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
        #w.grad means derivative of loss wrt w
        b -= learning_rate * b.grad
        #b.grad means derivative of loss wrt b
        w.grad.zero_()
        b.grad.zero_()
    print(w.item(), b.item())
  

1.0 1.0
1.67923104763031 -0.10242140293121338
2.058476209640503 -0.8362744450569153
2.659903049468994 -1.3721354007720947
2.7885499000549316 -1.6095430850982666
2.916172981262207 -1.779906988143921
2.952793598175049 -1.8686989545822144
2.9616856575012207 -1.9196808338165283
2.9688315391540527 -1.951175332069397
2.9864609241485596 -1.9729832410812378
2.9919486045837402 -1.9847029447555542


## Do it for a large problem

In [47]:
%%time
learning_rate = 0.001
N = 10000000
epochs = 200

w = torch.rand([N], requires_grad=True)
b = torch.ones([1], requires_grad=True)

# print(torch.mean(w).item(), b.item())

for i in range(epochs):
    x = torch.randn([N])
    y = torch.dot(3*torch.ones([N]), x) - 2
    y_hat = torch.dot(w, x) + b
    loss = torch.sum((y_hat - y)**2)
    loss.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()

#   print(torch.mean(w).item(), b.item())
  

Wall time: 1min 10s


In [48]:
%%time
learning_rate = 0.001
N = 10000000
epochs = 200

w = torch.rand([N], requires_grad=True, device=cuda0)
b = torch.ones([1], requires_grad=True, device=cuda0)

# print(torch.mean(w).item(), b.item())

for i in range(epochs):
    x = torch.randn([N], device=cuda0)
    y = torch.dot(3*torch.ones([N], device=cuda0), x) - 2
    y_hat = torch.dot(w, x) + b
    loss = torch.sum((y_hat - y)**2)
    loss.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()

  #print(torch.mean(w).item(), b.item())
#cuda0 increases time 

Wall time: 1.21 s
